# Generated by Django 4.1.6 on 2023-02-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertybook_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sllug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
