# Generated by Django 4.1.6 on 2023-02-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_sllug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='sllug',
            new_name='slug',
        ),
    ]
